# Generated by Django 6.1.1 on 2026-10-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('Today', 'Today')], default='upcoming', max_length=20),
        ),
    ]
